had to change select.js code so that it works
using the previous code i got this error

SqlError: (conn:-1, no: 45027, SQLState: HY000) Cannot add request to pool, pool is closed
sql: SELECT * from demo.contacts
    at Object.module.exports.createError (/home/camindo/Node/mariadbnodeconnection/node_modules/mariadb/lib/misc/errors.js:66:10)
    at /home/camindo/Node/mariadbnodeconnection/node_modules/mariadb/lib/pool.js:538:24 {
  sqlMessage: 'Cannot add request to pool, pool is closed',
  sql: 'SELECT * from demo.contacts',
  fatal: false,
  errno: 45027,
  sqlState: 'HY000',
  code: 'ER_POOL_ALREADY_CLOSED'